name: Test MCP Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test chat mode creation
      run: |
        python example_usage.py
        
    - name: Verify chat mode files created
      run: |
        ls -la .github/chatmodes/
        ls -la chat_modes/
        
    - name: Validate chat mode file format
      run: |
        echo "Checking front matter format..."
        head -5 .github/chatmodes/*.md
